import { PrismaClient } from "../generated/prisma";

const db = new PrismaClient();

function slugify(name: string): string {
  return name
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, "-")
    .replace(/(^-|-$)/g, "");
}

const weapons = [
  // === ASSAULT RIFLES ===
  {
    name: "Overrun AR",
    type: "ASSAULT_RIFLE" as const,
    slot: "PRIMARY" as const,
    ammoType: "LIGHT_ROUNDS" as const,
    rarity: "Standard",
    price: 50,
    description: "Light assault rifle with high rate of fire.",
    firepower: 14.7,
    damage: 10.5,
    precisionMultiplier: 1.4,
    rateOfFire: 720,
    range: 40,
    accuracy: 50.3,
    hipfireSpread: 2.32,
    adsSpread: 0.94,
    crouchSpreadBonus: 87.5,
    movingInaccuracy: 90.9,
    handling: 46,
    equipSpeed: 0.94,
    adsSpeed: 0.43,
    reloadSpeed: 2.37,
    weight: 32,
    recoil: 78.3,
    aimAssist: 1.68,
    magazineSize: 20,
    zoom: 1.2,
  },
  {
    name: "M77 Assault Rifle",
    type: "ASSAULT_RIFLE" as const,
    slot: "PRIMARY" as const,
    ammoType: "LIGHT_ROUNDS" as const,
    rarity: "Standard",
    price: 1200,
    description:
      "Ballistic assault rifle. Toggle the built-in flip scope for high precision.",
    firepower: 24,
    damage: 16,
    precisionMultiplier: 1.5,
    rateOfFire: 450,
    range: 46,
    accuracy: 59.3,
    hipfireSpread: 2.15,
    adsSpread: 0.98,
    crouchSpreadBonus: 80,
    movingInaccuracy: 32.7,
    handling: 38,
    equipSpeed: 0.94,
    adsSpeed: 0.5,
    reloadSpeed: 2.6,
    weight: 32,
    recoil: 114,
    aimAssist: 1.96,
    magazineSize: 24,
    zoom: 1.2,
  },
  {
    name: "Impact HAR",
    type: "ASSAULT_RIFLE" as const,
    slot: "PRIMARY" as const,
    ammoType: "HEAVY_ROUNDS" as const,
    rarity: "Standard",
    description:
      "The Impact HAR is a semi-automatic Assault Rifle that uses Heavy Rounds. This slower-firing weapon emphasizes stability and higher damage per shot.",
    firepower: 38.4,
    damage: 24,
    precisionMultiplier: 1.6,
    rateOfFire: 400,
    range: 60,
    accuracy: 48.5,
    hipfireSpread: 3.3,
    adsSpread: 0.48,
    crouchSpreadBonus: 80,
    movingInaccuracy: 90.9,
    handling: 36,
    equipSpeed: 0.9,
    adsSpeed: 0.8,
    reloadSpeed: 3.3,
    weight: 32,
    recoil: 100,
    aimAssist: 0.9,
    magazineSize: 18,
    zoom: 1.2,
  },
  {
    name: "V75 Scar",
    type: "ASSAULT_RIFLE" as const,
    slot: "PRIMARY" as const,
    ammoType: "VOLT_BATTERY" as const,
    rarity: "Standard",
    description:
      "Volt-actuated assault rifle with tracking projectiles. Sustained fire overheats the weapon, lowering its rate of fire.",
    firepower: 20.3,
    accuracy: 59.3,
    handling: 42,
    range: 46,
    zoom: 1.2,
    voltDrain: 2.5,
  },

  // === SUBMACHINE GUNS ===
  {
    name: "Bully SMG",
    type: "SMG" as const,
    slot: "PRIMARY" as const,
    ammoType: "HEAVY_ROUNDS" as const,
    rarity: "Standard",
    description: "Heavy ballistic submachine gun with brutal reputation.",
    firepower: 22.5,
    damage: 15,
    precisionMultiplier: 1.5,
    rateOfFire: 540,
    range: 27,
    accuracy: 62,
    hipfireSpread: 1.55,
    adsSpread: 1.36,
    crouchSpreadBonus: 80,
    movingInaccuracy: 17.7,
    handling: 47,
    equipSpeed: 0.9,
    adsSpeed: 0.35,
    reloadSpeed: 2.76,
    weight: 27.5,
    recoil: 82,
    aimAssist: 2.59,
    magazineSize: 23,
    zoom: 1.1,
  },
  {
    name: "V22 Volt Thrower",
    type: "SMG" as const,
    slot: "PRIMARY" as const,
    ammoType: "VOLT_BATTERY" as const,
    rarity: "Standard",
    description: "Volt-actuated submachine gun with smart lock-on system",
    firepower: 21,
    damage: 21,
    precisionMultiplier: 1.0,
    rateOfFire: 507,
    range: 11,
    accuracy: 74.1,
    hipfireSpread: 0.98,
    adsSpread: 0.45,
    crouchSpreadBonus: 80,
    movingInaccuracy: 20.5,
    handling: 42,
    equipSpeed: 0.9,
    adsSpeed: 0.4,
    reloadSpeed: 3.1,
    weight: 30,
    recoil: 98,
    aimAssist: 1.78,
    zoom: 1.4,
    voltDrain: 1.2,
  },
  {
    name: "BRRT SMG",
    type: "SMG" as const,
    slot: "PRIMARY" as const,
    ammoType: "LIGHT_ROUNDS" as const,
    rarity: "Standard",
    description:
      "Compact submachine gun with five-round burst firing mechanism.",
    firepower: 16.1,
    damage: 11,
    precisionMultiplier: 1.4,
    rateOfFire: 1000,
    range: 16,
    accuracy: 60.5,
    hipfireSpread: 1.93,
    adsSpread: 1.16,
    crouchSpreadBonus: 85,
    movingInaccuracy: 17.7,
    handling: 35,
    equipSpeed: 0.9,
    adsSpeed: 0.35,
    reloadSpeed: 3.0,
    weight: 27.5,
    recoil: 143.6,
    aimAssist: 2.44,
    magazineSize: 35,
    zoom: 1.1,
  },
  {
    name: "Copperhead RF",
    type: "SMG" as const,
    slot: "PRIMARY" as const,
    ammoType: "LIGHT_ROUNDS" as const,
    rarity: "Standard",
    description: "Light submachine gun with rapid semiautomatic fire.",
    firepower: 16.8,
    accuracy: 49.1,
    handling: 46,
    range: 15,
    magazineSize: 21,
    zoom: 1.1,
  },

  // === LIGHT MACHINE GUNS ===
  {
    name: "Conquest LMG",
    type: "LMG" as const,
    slot: "HEAVY" as const,
    ammoType: "LIGHT_ROUNDS" as const,
    rarity: "Standard",
    description:
      "Light machine gun with ramping rate of fire. Stability is increased while firing from crouched position.",
    firepower: 22.4,
    damage: 16,
    precisionMultiplier: 1.4,
    rateOfFire: 540,
    range: 60,
    accuracy: 49.9,
    hipfireSpread: 2.8,
    adsSpread: 0.85,
    crouchSpreadBonus: 70,
    movingInaccuracy: 90.9,
    handling: 22,
    equipSpeed: 1.2,
    adsSpeed: 0.8,
    reloadSpeed: 6.4,
    weight: 47.5,
    recoil: 90,
    aimAssist: 1.4,
    magazineSize: 36,
    zoom: 1.2,
  },
  {
    name: "Demolition HMG",
    type: "LMG" as const,
    slot: "HEAVY" as const,
    ammoType: "HEAVY_ROUNDS" as const,
    rarity: "Standard",
    description: "Heavy machine gun with moderate rate of fire.",
    firepower: 47.25,
    damage: 31.5,
    precisionMultiplier: 1.5,
    rateOfFire: 225,
    range: 33,
    accuracy: 47.34,
    hipfireSpread: 1.52,
    adsSpread: 1.16,
    crouchSpreadBonus: 80,
    movingInaccuracy: 20.5,
    handling: 31,
    equipSpeed: 1.2,
    adsSpeed: 0.76,
    reloadSpeed: 5.46,
    weight: 47.5,
    recoil: 57.5,
    aimAssist: 1.78,
    magazineSize: 20,
    zoom: 1.2,
  },
  {
    name: "Retaliator LMG",
    type: "LMG" as const,
    slot: "HEAVY" as const,
    ammoType: "LIGHT_ROUNDS" as const,
    rarity: "Standard",
    description: "Belt-fed light machine gun with high rate of fire.",
    firepower: 16.4,
    range: 51,
    accuracy: 49.8,
    handling: 25,
    magazineSize: 44,
    zoom: 1.2,
  },

  // === PISTOLS ===
  {
    name: "CE Tactical Sidearm",
    type: "PISTOL" as const,
    slot: "SECONDARY" as const,
    ammoType: "LIGHT_ROUNDS" as const,
    rarity: "Standard",
    description:
      "Light ballistic pistol with standard semiautomatic fire.",
    firepower: 36.0,
    damage: 20,
    precisionMultiplier: 1.8,
    rateOfFire: 300,
    range: 21,
    accuracy: 56.3,
    hipfireSpread: 1.47,
    adsSpread: 1.03,
    crouchSpreadBonus: 90,
    movingInaccuracy: 81.8,
    handling: 58,
    equipSpeed: 0.8,
    adsSpeed: 0.33,
    reloadSpeed: 2.1,
    weight: 26,
    recoil: 43,
    aimAssist: 1.55,
    magazineSize: 18,
    zoom: 1.1,
  },
  {
    name: "Magnum MC",
    type: "PISTOL" as const,
    slot: "SECONDARY" as const,
    ammoType: "HEAVY_ROUNDS" as const,
    rarity: "Standard",
    description:
      "Heavy pistol equipped with modular muzzle and optics rail.",
    firepower: 66.0,
    damage: 33,
    precisionMultiplier: 2.1,
    rateOfFire: 138,
    range: 21,
    accuracy: 58.3,
    hipfireSpread: 1.39,
    adsSpread: 0.38,
    crouchSpreadBonus: 90,
    movingInaccuracy: 90.9,
    handling: 50,
    equipSpeed: 0.8,
    adsSpeed: 0.38,
    reloadSpeed: 1.9,
    weight: 28,
    recoil: 81.5,
    aimAssist: 1.28,
    magazineSize: 12,
    zoom: 1.4,
  },
  {
    name: "V11 Punch",
    type: "PISTOL" as const,
    slot: "SECONDARY" as const,
    ammoType: "VOLT_BATTERY" as const,
    rarity: "Standard",
    description:
      "Volt-actuated pistol. Tap for semiautomatic fire or hold to build and release a high-damage burst.",
    firepower: 37.5,
    damage: 20,
    precisionMultiplier: 1.5,
    rateOfFire: 600,
    range: 21,
    accuracy: 36,
    hipfireSpread: 3.13,
    adsSpread: 1.72,
    crouchSpreadBonus: 90,
    movingInaccuracy: 100,
    handling: 44,
    equipSpeed: 0.8,
    adsSpeed: 0.3,
    reloadSpeed: 3.4,
    weight: 37,
    recoil: 76.5,
    aimAssist: 2.04,
    zoom: 1.1,
    voltDrain: 2.5,
  },

  // === SNIPER RIFLES ===
  {
    name: "Longshot",
    type: "SNIPER_RIFLE" as const,
    slot: "SECONDARY" as const,
    ammoType: "MIPS_ROUNDS" as const,
    rarity: "Standard",
    description:
      "The Longshot is a Sniper Rifle that uses MIPS Rounds. It excels at long range assassinations.",
    firepower: 140,
    damage: 70,
    precisionMultiplier: 2.0,
    rateOfFire: 50,
    range: 175,
    accuracy: 74.8,
    hipfireSpread: 6.75,
    adsSpread: 0,
    crouchSpreadBonus: 60,
    movingInaccuracy: 90.9,
    handling: 29,
    equipSpeed: 1.7,
    adsSpeed: 1.1,
    reloadSpeed: 4.7,
    weight: 38,
    recoil: 60,
    aimAssist: 0.3,
    magazineSize: 3,
    zoom: 4.0,
  },
  {
    name: "V99 Channel Rifle",
    type: "SNIPER_RIFLE" as const,
    slot: "SECONDARY" as const,
    ammoType: "VOLT_CELL" as const,
    rarity: "Standard",
    description:
      "Powerful volt sniper rifle that charges up for increased damage while scoped. Hits almost instantly at long range.",
    firepower: 120.0,
    accuracy: 71.2,
    handling: 29,
    range: 175,
    zoom: 4.0,
    voltDrain: 29,
  },
  {
    name: "Outland",
    type: "SNIPER_RIFLE" as const,
    slot: "SECONDARY" as const,
    ammoType: "MIPS_ROUNDS" as const,
    rarity: "Standard",
    description:
      "Ballistic bolt-action sniper rifle. Extreme damage and range.",
  },

  // === SHOTGUNS ===
  {
    name: "WSTR Combat Shotgun",
    type: "SHOTGUN" as const,
    slot: "SECONDARY" as const,
    ammoType: "MIPS_ROUNDS" as const,
    rarity: "Standard",
    description:
      "The WSTR Combat Shotgun is a double-barrel Shotgun that uses MIPS Rounds. It packs high damage in close quarters.",
    firepower: 172.5,
    damage: 11,
    precisionMultiplier: 1.5,
    rateOfFire: 1.3,
    range: 8,
    accuracy: 50,
    hipfireSpread: 45,
    handling: 45,
    equipSpeed: 0.9,
    adsSpeed: 0.42,
    reloadSpeed: 2.6,
    weight: 36,
    recoil: 73,
    aimAssist: 3.15,
    magazineSize: 2,
    zoom: 1.1,
    pelletCount: 10,
    spreadAngle: 2.4,
  },
  {
    name: "Misriah 2442",
    type: "SHOTGUN" as const,
    slot: "SECONDARY" as const,
    ammoType: "MIPS_ROUNDS" as const,
    rarity: "Standard",
    description:
      "Pump-action shotgun kept for close encounters. Reloads one MIPS cartridge at a time.",
  },
  {
    name: "V85 Circuit Breaker",
    type: "SHOTGUN" as const,
    slot: "SECONDARY" as const,
    ammoType: "VOLT_CELL" as const,
    rarity: "Standard",
    description:
      "Fixed-pattern heavy volt shotgun. Can be charged up to three levels.",
    firepower: 220.0,
    handling: 42,
    range: 14,
    spreadAngle: 1.7,
    zoom: 1.1,
  },

  // === PRECISION RIFLES ===
  {
    name: "Hardline PR",
    type: "PRECISION_RIFLE" as const,
    slot: "PRIMARY" as const,
    ammoType: "LIGHT_ROUNDS" as const,
    rarity: "Standard",
    description:
      "Single-round semiautomatic precision rifle with high rate of fire",
    firepower: 50.4,
    damage: 28,
    precisionMultiplier: 1.8,
    rateOfFire: 275,
    range: 69,
    accuracy: 65.1,
    hipfireSpread: 2.35,
    adsSpread: 0.44,
    crouchSpreadBonus: 60,
    movingInaccuracy: 20.5,
    handling: 36,
    equipSpeed: 0.94,
    adsSpeed: 0.45,
    reloadSpeed: 3.6,
    weight: 37,
    recoil: 103.2,
    aimAssist: 1.01,
    magazineSize: 16,
    zoom: 1.2,
  },
  {
    name: "Repeater HPR",
    type: "PRECISION_RIFLE" as const,
    slot: "PRIMARY" as const,
    ammoType: "HEAVY_ROUNDS" as const,
    rarity: "Standard",
    description:
      "Lever-action heavy precision rifle. Reloads one round at a time.",
    firepower: 48,
    damage: 48,
    precisionMultiplier: 2.0,
    rateOfFire: 86,
    range: 37,
    accuracy: 60.4,
    hipfireSpread: 2.65,
    adsSpread: 0.92,
    crouchSpreadBonus: 60,
    movingInaccuracy: 20.5,
    handling: 52,
    equipSpeed: 0.9,
    adsSpeed: 0.34,
    reloadSpeed: 0.9,
    weight: 37,
    recoil: 57.8,
    aimAssist: 1.01,
    magazineSize: 9,
    zoom: 1.2,
  },
  {
    name: "Twin Tap HBR",
    type: "PRECISION_RIFLE" as const,
    slot: "PRIMARY" as const,
    ammoType: "HEAVY_ROUNDS" as const,
    rarity: "Standard",
    description:
      "Burst-fire heavy ballistic precision rifle with dual-round delivery system.",
    firepower: 25,
    damage: 13,
    precisionMultiplier: 1.6,
    rateOfFire: 420,
    range: 48,
    accuracy: 59.8,
    hipfireSpread: 2.24,
    adsSpread: 1.29,
    crouchSpreadBonus: 0,
    movingInaccuracy: 81.8,
    handling: 51,
    equipSpeed: 0.94,
    adsSpeed: 0.35,
    reloadSpeed: 2.37,
    weight: 37.5,
    recoil: 44.9,
    aimAssist: 1.1,
    magazineSize: 20,
    zoom: 1.4,
  },
  {
    name: "Stryder M1T",
    type: "PRECISION_RIFLE" as const,
    slot: "PRIMARY" as const,
    ammoType: "LIGHT_ROUNDS" as const,
    rarity: "Standard",
    description: "Fine-tuned semiautomatic precision rifle.",
    firepower: 46.5,
    accuracy: 59.4,
    handling: 39,
    range: 84,
    magazineSize: 12,
    zoom: 1.4,
  },
  {
    name: "V66 Lookout",
    type: "PRECISION_RIFLE" as const,
    slot: "PRIMARY" as const,
    ammoType: "VOLT_BATTERY" as const,
    rarity: "Standard",
    description:
      "Volt-actuated precision rifle with tracking projectiles. Sustained fire overheats the weapon, lowering its rate of fire.",
    firepower: 46.8,
    range: 88,
    accuracy: 66,
    handling: 46,
    zoom: 1.4,
    voltDrain: 3.4,
  },
  {
    name: "B33 Volley Rifle",
    type: "PRECISION_RIFLE" as const,
    slot: "PRIMARY" as const,
    ammoType: "LIGHT_ROUNDS" as const,
    rarity: "Standard",
    description:
      "Semiautomatic precision rifle with three-round burst fire.",
    firepower: 20.7,
    range: 48,
    accuracy: 61.2,
    handling: 45,
    magazineSize: 27,
    zoom: 1.4,
  },

  // === RAILGUNS ===
  {
    name: "V00 Zeus RG",
    type: "RAILGUN" as const,
    slot: "HEAVY" as const,
    ammoType: "VOLT_CELL" as const,
    rarity: "Standard",
    description:
      "Anti-materiel railgun. Fires automatically once fully charged.",
    firepower: 196.5,
    damage: 120,
    precisionMultiplier: 1.5,
    rateOfFire: 90,
    range: 155,
    accuracy: 74.8,
    hipfireSpread: 4.1,
    adsSpread: 0,
    crouchSpreadBonus: 60,
    movingInaccuracy: 90.9,
    handling: 49,
    equipSpeed: 0.9,
    adsSpeed: 0.55,
    reloadSpeed: 3.5,
    weight: 20,
    recoil: 100,
    aimAssist: 1.65,
    zoom: 2.5,
    voltDrain: 50,
    chargeTime: 0.75,
  },
  {
    name: "Ares RG",
    type: "RAILGUN" as const,
    slot: "HEAVY" as const,
    ammoType: "MIPS_ROUNDS" as const,
    rarity: "Standard",
    description:
      "Heavy ballistic railgun. Charges up to fire massive projectile at extreme velocity.",
    firepower: 159.9,
    accuracy: 100.0,
    handling: 47,
    range: 55,
    magazineSize: 4,
    zoom: 2.5,
  },
];

async function main() {
  console.log(`Seeding ${weapons.length} weapons...`);

  for (const weapon of weapons) {
    const slug = slugify(weapon.name);
    const imageUrl = `/weapons/${slug}.png`;
    await db.weapon.upsert({
      where: { name: weapon.name },
      update: { ...weapon, slug, imageUrl },
      create: { ...weapon, slug, imageUrl },
    });
    console.log(`  ✓ ${weapon.name}`);
  }

  console.log(`\nSeeded ${weapons.length} weapons.`);

  // === MODS ===
  const mods: {
    name: string;
    type: "BARREL" | "GRIP" | "MAGAZINE" | "OPTIC" | "SHIELD" | "GENERATOR" | "CHIP";
    rarity: "PRESTIGE" | "SUPERIOR" | "DELUXE" | "ENHANCED" | "STANDARD";
    isUniversal?: boolean;
    compatibleWeapons: string[];
  }[] = [
    // --- BARREL (14) ---
    { name: "Flechette Split Action", type: "BARREL", rarity: "PRESTIGE", compatibleWeapons: ["WSTR Combat Shotgun", "BRRT SMG"] },
    { name: "Lockout Muzzle Brake", type: "BARREL", rarity: "PRESTIGE", compatibleWeapons: ["B33 Volley Rifle"] },
    { name: "MIPS Slug Converter", type: "BARREL", rarity: "PRESTIGE", compatibleWeapons: ["WSTR Combat Shotgun"] },
    { name: "Pinpoint Barrel", type: "BARREL", rarity: "SUPERIOR", compatibleWeapons: ["Misriah 2442", "WSTR Combat Shotgun"] },
    { name: "Steady Barrel", type: "BARREL", rarity: "SUPERIOR", compatibleWeapons: ["Hardline PR", "Repeater HPR", "Stryder M1T", "Twin Tap HBR", "Longshot", "Outland"] },
    { name: "Precision Barrel", type: "BARREL", rarity: "DELUXE", compatibleWeapons: ["CE Tactical Sidearm", "Magnum MC", "Bully SMG", "BRRT SMG", "Copperhead RF"] },
    { name: "Precision Choke", type: "BARREL", rarity: "DELUXE", compatibleWeapons: ["Misriah 2442", "WSTR Combat Shotgun"] },
    { name: "Suppression Dampener", type: "BARREL", rarity: "DELUXE", compatibleWeapons: [] },
    { name: "Farshot Barrel", type: "BARREL", rarity: "ENHANCED", compatibleWeapons: [] },
    { name: "Impulse Brake", type: "BARREL", rarity: "ENHANCED", compatibleWeapons: [] },
    { name: "Ironhold Barrel", type: "BARREL", rarity: "ENHANCED", compatibleWeapons: ["CE Tactical Sidearm", "Magnum MC", "Bully SMG", "BRRT SMG", "Copperhead RF"] },
    { name: "Stabilizing Barrel", type: "BARREL", rarity: "ENHANCED", compatibleWeapons: ["V66 Lookout", "V99 Channel Rifle"] },
    { name: "Weighted Barrel", type: "BARREL", rarity: "ENHANCED", compatibleWeapons: ["CE Tactical Sidearm", "Magnum MC", "Bully SMG", "BRRT SMG", "Copperhead RF"] },
    { name: "Nano-Suppressor", type: "BARREL", rarity: "ENHANCED", compatibleWeapons: ["CE Tactical Sidearm", "Magnum MC", "Bully SMG", "BRRT SMG", "Copperhead RF"] },

    // --- GRIP (2) ---
    { name: "Combat Grip", type: "GRIP", rarity: "DELUXE", compatibleWeapons: ["Impact HAR", "M77 Assault Rifle", "Overrun AR", "V75 Scar"] },
    { name: "Snapshot Grip", type: "GRIP", rarity: "DELUXE", compatibleWeapons: ["Misriah 2442", "V85 Circuit Breaker", "WSTR Combat Shotgun"] },

    // --- MAGAZINE (10) ---
    { name: "Adrenal Feedback Rounds", type: "MAGAZINE", rarity: "PRESTIGE", compatibleWeapons: ["Hardline PR"] },
    { name: "Kingmaker Mag", type: "MAGAZINE", rarity: "PRESTIGE", compatibleWeapons: ["Longshot"] },
    { name: "Overclocked Delimiter", type: "MAGAZINE", rarity: "PRESTIGE", compatibleWeapons: ["V85 Circuit Breaker"] },
    { name: "Ram-Page Mag", type: "MAGAZINE", rarity: "PRESTIGE", compatibleWeapons: ["V75 Scar"] },
    { name: "Rodeo Mag", type: "MAGAZINE", rarity: "PRESTIGE", compatibleWeapons: ["WSTR Combat Shotgun", "Bully SMG"] },
    { name: "Air-Cooled Chamber", type: "MAGAZINE", rarity: "SUPERIOR", compatibleWeapons: ["V00 Zeus RG", "V85 Circuit Breaker", "V99 Channel Rifle"] },
    { name: "Hi-Cap Mag", type: "MAGAZINE", rarity: "DELUXE", compatibleWeapons: ["B33 Volley Rifle", "Hardline PR", "Stryder M1T", "Twin Tap HBR", "Longshot"] },
    { name: "Slick Mag I", type: "MAGAZINE", rarity: "ENHANCED", compatibleWeapons: ["Misriah 2442"] },
    { name: "Steady Mag", type: "MAGAZINE", rarity: "ENHANCED", compatibleWeapons: ["CE Tactical Sidearm"] },
    { name: "Turbo Chamber", type: "MAGAZINE", rarity: "ENHANCED", compatibleWeapons: ["V66 Lookout", "V11 Punch", "V22 Volt Thrower"] },

    // --- OPTIC (5) ---
    { name: "Lever Overhaul Interface", type: "OPTIC", rarity: "PRESTIGE", compatibleWeapons: ["Repeater HPR"] },
    { name: "Pistol Scope", type: "OPTIC", rarity: "PRESTIGE", compatibleWeapons: ["Magnum MC"] },
    { name: "Vital Intel", type: "OPTIC", rarity: "PRESTIGE", compatibleWeapons: ["Stryder M1T"] },
    { name: "Far Reach Optic", type: "OPTIC", rarity: "DELUXE", compatibleWeapons: ["Impact HAR", "Overrun AR", "V75 Scar", "Bully SMG", "BRRT SMG", "Copperhead RF"] },
    { name: "Termal Optic", type: "OPTIC", rarity: "DELUXE", compatibleWeapons: ["B33 Volley Rifle", "Hardline PR", "Repeater HPR", "Stryder M1T", "Twin Tap HBR", "V66 Lookout"] },

    // --- SHIELD (4) ---
    { name: "Circuit Shield", type: "SHIELD", rarity: "PRESTIGE", compatibleWeapons: ["Retaliator LMG"] },
    { name: "Control Shield", type: "SHIELD", rarity: "SUPERIOR", compatibleWeapons: ["Conquest LMG", "Demolition HMG", "Retaliator LMG"] },
    { name: "Balanced Shield", type: "SHIELD", rarity: "DELUXE", compatibleWeapons: ["Conquest LMG", "Demolition HMG", "Retaliator LMG"] },
    { name: "Duelist Shield", type: "SHIELD", rarity: "ENHANCED", compatibleWeapons: ["Conquest LMG", "Demolition HMG", "Retaliator LMG"] },

    // --- GENERATOR (2) ---
    { name: "Overclocked Generator", type: "GENERATOR", rarity: "PRESTIGE", compatibleWeapons: ["V00 Zeus RG"] },
    { name: "Stabilizing Generator", type: "GENERATOR", rarity: "SUPERIOR", compatibleWeapons: ["Ares RG", "V00 Zeus RG"] },

    // --- CHIP (9: 8 universal + 1 non-universal) ---
    { name: "See ya", type: "CHIP", rarity: "SUPERIOR", isUniversal: true, compatibleWeapons: [] },
    { name: "Bounty", type: "CHIP", rarity: "DELUXE", isUniversal: true, compatibleWeapons: [] },
    { name: "Torch Bug", type: "CHIP", rarity: "DELUXE", isUniversal: true, compatibleWeapons: [] },
    { name: "Bounty Hunter", type: "CHIP", rarity: "ENHANCED", isUniversal: true, compatibleWeapons: [] },
    { name: "Swarm Directive", type: "CHIP", rarity: "ENHANCED", isUniversal: true, compatibleWeapons: [] },
    { name: "Last Resort", type: "CHIP", rarity: "ENHANCED", isUniversal: true, compatibleWeapons: [] },
    { name: "Eyes On Fire", type: "CHIP", rarity: "STANDARD", isUniversal: true, compatibleWeapons: [] },
    { name: "Endless Runner", type: "CHIP", rarity: "STANDARD", isUniversal: true, compatibleWeapons: [] },
    { name: "Veilshot Chip", type: "CHIP", rarity: "ENHANCED", compatibleWeapons: ["Conquest LMG", "V85 Circuit Breaker"] },
  ];

  console.log(`\nSeeding ${mods.length} mods...`);

  // Build weapon name → id lookup
  const allWeapons = await db.weapon.findMany({ select: { id: true, name: true } });
  const weaponMap = new Map(allWeapons.map((w) => [w.name, w.id]));

  for (const mod of mods) {
    const slug = slugify(mod.name);
    const upserted = await db.mod.upsert({
      where: { name: mod.name },
      update: { slug, type: mod.type, rarity: mod.rarity, isUniversal: mod.isUniversal ?? false },
      create: { name: mod.name, slug, type: mod.type, rarity: mod.rarity, isUniversal: mod.isUniversal ?? false },
    });

    // Create junction rows for non-universal mods
    for (const weaponName of mod.compatibleWeapons) {
      const weaponId = weaponMap.get(weaponName);
      if (!weaponId) {
        console.warn(`  ⚠ Weapon not found: "${weaponName}" (mod: ${mod.name})`);
        continue;
      }
      await db.weaponMod.upsert({
        where: { weaponId_modId: { weaponId, modId: upserted.id } },
        update: {},
        create: { weaponId, modId: upserted.id },
      });
    }

    console.log(`  ✓ ${mod.name} (${mod.compatibleWeapons.length} weapons)`);
  }

  console.log(`\nSeeded ${mods.length} mods.`);
}

main()
  .then(() => db.$disconnect())
  .catch(async (e) => {
    console.error(e);
    await db.$disconnect();
    process.exit(1);
  });
