import { PrismaClient } from "../generated/prisma";

const db = new PrismaClient();

function slugify(name: string): string {
  return name
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, "-")
    .replace(/(^-|-$)/g, "");
}

const weapons = [
  // === ASSAULT RIFLES ===
  {
    name: "Overrun AR",
    type: "ASSAULT_RIFLE" as const,
    slot: "PRIMARY" as const,
    ammoType: "LIGHT_ROUNDS" as const,
    rarity: "Standard",
    price: 50,
    description: "Light assault rifle with high rate of fire.",
    firepower: 14.7,
    damage: 10.5,
    precisionMultiplier: 1.4,
    rateOfFire: 720,
    range: 40,
    accuracy: 50.3,
    hipfireSpread: 2.32,
    adsSpread: 0.94,
    crouchSpreadBonus: 87.5,
    movingInaccuracy: 90.9,
    handling: 46,
    equipSpeed: 0.94,
    adsSpeed: 0.43,
    reloadSpeed: 2.37,
    weight: 32,
    recoil: 78.3,
    aimAssist: 1.68,
    magazineSize: 20,
    zoom: 1.2,
  },
  {
    name: "M77 Assault Rifle",
    type: "ASSAULT_RIFLE" as const,
    slot: "PRIMARY" as const,
    ammoType: "LIGHT_ROUNDS" as const,
    rarity: "Standard",
    price: 1200,
    description:
      "Ballistic assault rifle. Toggle the built-in flip scope for high precision.",
    firepower: 24,
    damage: 16,
    precisionMultiplier: 1.5,
    rateOfFire: 450,
    range: 46,
    accuracy: 59.3,
    hipfireSpread: 2.15,
    adsSpread: 0.98,
    crouchSpreadBonus: 80,
    movingInaccuracy: 32.7,
    handling: 38,
    equipSpeed: 0.94,
    adsSpeed: 0.5,
    reloadSpeed: 2.6,
    weight: 32,
    recoil: 114,
    aimAssist: 1.96,
    magazineSize: 24,
    zoom: 1.2,
  },
  {
    name: "Impact HAR",
    type: "ASSAULT_RIFLE" as const,
    slot: "PRIMARY" as const,
    ammoType: "HEAVY_ROUNDS" as const,
    rarity: "Standard",
    description:
      "The Impact HAR is a semi-automatic Assault Rifle that uses Heavy Rounds. This slower-firing weapon emphasizes stability and higher damage per shot.",
    firepower: 38.4,
    damage: 24,
    precisionMultiplier: 1.6,
    rateOfFire: 400,
    range: 60,
    accuracy: 48.5,
    hipfireSpread: 3.3,
    adsSpread: 0.48,
    crouchSpreadBonus: 80,
    movingInaccuracy: 90.9,
    handling: 36,
    equipSpeed: 0.9,
    adsSpeed: 0.8,
    reloadSpeed: 3.3,
    weight: 32,
    recoil: 100,
    aimAssist: 0.9,
    magazineSize: 18,
    zoom: 1.2,
  },
  {
    name: "V75 Scar",
    type: "ASSAULT_RIFLE" as const,
    slot: "PRIMARY" as const,
    ammoType: "VOLT_BATTERY" as const,
    rarity: "Standard",
    description:
      "Volt-actuated assault rifle with tracking projectiles. Sustained fire overheats the weapon, lowering its rate of fire.",
    firepower: 20.3,
    accuracy: 59.3,
    handling: 42,
    range: 46,
    zoom: 1.2,
    voltDrain: 2.5,
  },

  // === SUBMACHINE GUNS ===
  {
    name: "Bully SMG",
    type: "SMG" as const,
    slot: "PRIMARY" as const,
    ammoType: "HEAVY_ROUNDS" as const,
    rarity: "Standard",
    description: "Heavy ballistic submachine gun with brutal reputation.",
    firepower: 22.5,
    damage: 15,
    precisionMultiplier: 1.5,
    rateOfFire: 540,
    range: 27,
    accuracy: 62,
    hipfireSpread: 1.55,
    adsSpread: 1.36,
    crouchSpreadBonus: 80,
    movingInaccuracy: 17.7,
    handling: 47,
    equipSpeed: 0.9,
    adsSpeed: 0.35,
    reloadSpeed: 2.76,
    weight: 27.5,
    recoil: 82,
    aimAssist: 2.59,
    magazineSize: 23,
    zoom: 1.1,
  },
  {
    name: "V22 Volt Thrower",
    type: "SMG" as const,
    slot: "PRIMARY" as const,
    ammoType: "VOLT_BATTERY" as const,
    rarity: "Standard",
    description: "Volt-actuated submachine gun with smart lock-on system",
    firepower: 21,
    damage: 21,
    precisionMultiplier: 1.0,
    rateOfFire: 507,
    range: 11,
    accuracy: 74.1,
    hipfireSpread: 0.98,
    adsSpread: 0.45,
    crouchSpreadBonus: 80,
    movingInaccuracy: 20.5,
    handling: 42,
    equipSpeed: 0.9,
    adsSpeed: 0.4,
    reloadSpeed: 3.1,
    weight: 30,
    recoil: 98,
    aimAssist: 1.78,
    zoom: 1.4,
    voltDrain: 1.2,
  },
  {
    name: "BRRT SMG",
    type: "SMG" as const,
    slot: "PRIMARY" as const,
    ammoType: "LIGHT_ROUNDS" as const,
    rarity: "Standard",
    description:
      "Compact submachine gun with five-round burst firing mechanism.",
    firepower: 16.1,
    damage: 11,
    precisionMultiplier: 1.4,
    rateOfFire: 1000,
    range: 16,
    accuracy: 60.5,
    hipfireSpread: 1.93,
    adsSpread: 1.16,
    crouchSpreadBonus: 85,
    movingInaccuracy: 17.7,
    handling: 35,
    equipSpeed: 0.9,
    adsSpeed: 0.35,
    reloadSpeed: 3.0,
    weight: 27.5,
    recoil: 143.6,
    aimAssist: 2.44,
    magazineSize: 35,
    zoom: 1.1,
  },
  {
    name: "Copperhead RF",
    type: "SMG" as const,
    slot: "PRIMARY" as const,
    ammoType: "LIGHT_ROUNDS" as const,
    rarity: "Standard",
    description: "Light submachine gun with rapid semiautomatic fire.",
    firepower: 16.8,
    accuracy: 49.1,
    handling: 46,
    range: 15,
    magazineSize: 21,
    zoom: 1.1,
  },

  // === LIGHT MACHINE GUNS ===
  {
    name: "Conquest LMG",
    type: "LMG" as const,
    slot: "HEAVY" as const,
    ammoType: "LIGHT_ROUNDS" as const,
    rarity: "Standard",
    description:
      "Light machine gun with ramping rate of fire. Stability is increased while firing from crouched position.",
    firepower: 22.4,
    damage: 16,
    precisionMultiplier: 1.4,
    rateOfFire: 540,
    range: 60,
    accuracy: 49.9,
    hipfireSpread: 2.8,
    adsSpread: 0.85,
    crouchSpreadBonus: 70,
    movingInaccuracy: 90.9,
    handling: 22,
    equipSpeed: 1.2,
    adsSpeed: 0.8,
    reloadSpeed: 6.4,
    weight: 47.5,
    recoil: 90,
    aimAssist: 1.4,
    magazineSize: 36,
    zoom: 1.2,
  },
  {
    name: "Demolition HMG",
    type: "LMG" as const,
    slot: "HEAVY" as const,
    ammoType: "HEAVY_ROUNDS" as const,
    rarity: "Standard",
    description: "Heavy machine gun with moderate rate of fire.",
    firepower: 47.25,
    damage: 31.5,
    precisionMultiplier: 1.5,
    rateOfFire: 225,
    range: 33,
    accuracy: 47.34,
    hipfireSpread: 1.52,
    adsSpread: 1.16,
    crouchSpreadBonus: 80,
    movingInaccuracy: 20.5,
    handling: 31,
    equipSpeed: 1.2,
    adsSpeed: 0.76,
    reloadSpeed: 5.46,
    weight: 47.5,
    recoil: 57.5,
    aimAssist: 1.78,
    magazineSize: 20,
    zoom: 1.2,
  },
  {
    name: "Retaliator LMG",
    type: "LMG" as const,
    slot: "HEAVY" as const,
    ammoType: "LIGHT_ROUNDS" as const,
    rarity: "Standard",
    description: "Belt-fed light machine gun with high rate of fire.",
    firepower: 16.4,
    range: 51,
    accuracy: 49.8,
    handling: 25,
    magazineSize: 44,
    zoom: 1.2,
  },

  // === PISTOLS ===
  {
    name: "CE Tactical Sidearm",
    type: "PISTOL" as const,
    slot: "SECONDARY" as const,
    ammoType: "LIGHT_ROUNDS" as const,
    rarity: "Standard",
    description:
      "Light ballistic pistol with standard semiautomatic fire.",
    firepower: 36.0,
    damage: 20,
    precisionMultiplier: 1.8,
    rateOfFire: 300,
    range: 21,
    accuracy: 56.3,
    hipfireSpread: 1.47,
    adsSpread: 1.03,
    crouchSpreadBonus: 90,
    movingInaccuracy: 81.8,
    handling: 58,
    equipSpeed: 0.8,
    adsSpeed: 0.33,
    reloadSpeed: 2.1,
    weight: 26,
    recoil: 43,
    aimAssist: 1.55,
    magazineSize: 18,
    zoom: 1.1,
  },
  {
    name: "Magnum MC",
    type: "PISTOL" as const,
    slot: "SECONDARY" as const,
    ammoType: "HEAVY_ROUNDS" as const,
    rarity: "Standard",
    description:
      "Heavy pistol equipped with modular muzzle and optics rail.",
    firepower: 66.0,
    damage: 33,
    precisionMultiplier: 2.1,
    rateOfFire: 138,
    range: 21,
    accuracy: 58.3,
    hipfireSpread: 1.39,
    adsSpread: 0.38,
    crouchSpreadBonus: 90,
    movingInaccuracy: 90.9,
    handling: 50,
    equipSpeed: 0.8,
    adsSpeed: 0.38,
    reloadSpeed: 1.9,
    weight: 28,
    recoil: 81.5,
    aimAssist: 1.28,
    magazineSize: 12,
    zoom: 1.4,
  },
  {
    name: "V11 Punch",
    type: "PISTOL" as const,
    slot: "SECONDARY" as const,
    ammoType: "VOLT_BATTERY" as const,
    rarity: "Standard",
    description:
      "Volt-actuated pistol. Tap for semiautomatic fire or hold to build and release a high-damage burst.",
    firepower: 37.5,
    damage: 20,
    precisionMultiplier: 1.5,
    rateOfFire: 600,
    range: 21,
    accuracy: 36,
    hipfireSpread: 3.13,
    adsSpread: 1.72,
    crouchSpreadBonus: 90,
    movingInaccuracy: 100,
    handling: 44,
    equipSpeed: 0.8,
    adsSpeed: 0.3,
    reloadSpeed: 3.4,
    weight: 37,
    recoil: 76.5,
    aimAssist: 2.04,
    zoom: 1.1,
    voltDrain: 2.5,
  },

  // === SNIPER RIFLES ===
  {
    name: "Longshot",
    type: "SNIPER_RIFLE" as const,
    slot: "SECONDARY" as const,
    ammoType: "MIPS_ROUNDS" as const,
    rarity: "Standard",
    description:
      "The Longshot is a Sniper Rifle that uses MIPS Rounds. It excels at long range assassinations.",
    firepower: 140,
    damage: 70,
    precisionMultiplier: 2.0,
    rateOfFire: 50,
    range: 175,
    accuracy: 74.8,
    hipfireSpread: 6.75,
    adsSpread: 0,
    crouchSpreadBonus: 60,
    movingInaccuracy: 90.9,
    handling: 29,
    equipSpeed: 1.7,
    adsSpeed: 1.1,
    reloadSpeed: 4.7,
    weight: 38,
    recoil: 60,
    aimAssist: 0.3,
    magazineSize: 3,
    zoom: 4.0,
  },
  {
    name: "V99 Channel Rifle",
    type: "SNIPER_RIFLE" as const,
    slot: "SECONDARY" as const,
    ammoType: "VOLT_CELL" as const,
    rarity: "Standard",
    description:
      "Powerful volt sniper rifle that charges up for increased damage while scoped. Hits almost instantly at long range.",
    firepower: 120.0,
    accuracy: 71.2,
    handling: 29,
    range: 175,
    zoom: 4.0,
    voltDrain: 29,
  },
  {
    name: "Outland",
    type: "SNIPER_RIFLE" as const,
    slot: "SECONDARY" as const,
    ammoType: "MIPS_ROUNDS" as const,
    rarity: "Standard",
    description:
      "Ballistic bolt-action sniper rifle. Extreme damage and range.",
  },

  // === SHOTGUNS ===
  {
    name: "WSTR Combat Shotgun",
    type: "SHOTGUN" as const,
    slot: "SECONDARY" as const,
    ammoType: "MIPS_ROUNDS" as const,
    rarity: "Standard",
    description:
      "The WSTR Combat Shotgun is a double-barrel Shotgun that uses MIPS Rounds. It packs high damage in close quarters.",
    firepower: 172.5,
    damage: 11,
    precisionMultiplier: 1.5,
    rateOfFire: 1.3,
    range: 8,
    accuracy: 50,
    hipfireSpread: 45,
    handling: 45,
    equipSpeed: 0.9,
    adsSpeed: 0.42,
    reloadSpeed: 2.6,
    weight: 36,
    recoil: 73,
    aimAssist: 3.15,
    magazineSize: 2,
    zoom: 1.1,
    pelletCount: 10,
    spreadAngle: 2.4,
  },
  {
    name: "Misriah 2442",
    type: "SHOTGUN" as const,
    slot: "SECONDARY" as const,
    ammoType: "MIPS_ROUNDS" as const,
    rarity: "Standard",
    description:
      "Pump-action shotgun kept for close encounters. Reloads one MIPS cartridge at a time.",
  },
  {
    name: "V85 Circuit Breaker",
    type: "SHOTGUN" as const,
    slot: "SECONDARY" as const,
    ammoType: "VOLT_CELL" as const,
    rarity: "Standard",
    description:
      "Fixed-pattern heavy volt shotgun. Can be charged up to three levels.",
    firepower: 220.0,
    handling: 42,
    range: 14,
    spreadAngle: 1.7,
    zoom: 1.1,
  },

  // === PRECISION RIFLES ===
  {
    name: "Hardline PR",
    type: "PRECISION_RIFLE" as const,
    slot: "PRIMARY" as const,
    ammoType: "LIGHT_ROUNDS" as const,
    rarity: "Standard",
    description:
      "Single-round semiautomatic precision rifle with high rate of fire",
    firepower: 50.4,
    damage: 28,
    precisionMultiplier: 1.8,
    rateOfFire: 275,
    range: 69,
    accuracy: 65.1,
    hipfireSpread: 2.35,
    adsSpread: 0.44,
    crouchSpreadBonus: 60,
    movingInaccuracy: 20.5,
    handling: 36,
    equipSpeed: 0.94,
    adsSpeed: 0.45,
    reloadSpeed: 3.6,
    weight: 37,
    recoil: 103.2,
    aimAssist: 1.01,
    magazineSize: 16,
    zoom: 1.2,
  },
  {
    name: "Repeater HPR",
    type: "PRECISION_RIFLE" as const,
    slot: "PRIMARY" as const,
    ammoType: "HEAVY_ROUNDS" as const,
    rarity: "Standard",
    description:
      "Lever-action heavy precision rifle. Reloads one round at a time.",
    firepower: 48,
    damage: 48,
    precisionMultiplier: 2.0,
    rateOfFire: 86,
    range: 37,
    accuracy: 60.4,
    hipfireSpread: 2.65,
    adsSpread: 0.92,
    crouchSpreadBonus: 60,
    movingInaccuracy: 20.5,
    handling: 52,
    equipSpeed: 0.9,
    adsSpeed: 0.34,
    reloadSpeed: 0.9,
    weight: 37,
    recoil: 57.8,
    aimAssist: 1.01,
    magazineSize: 9,
    zoom: 1.2,
  },
  {
    name: "Twin Tap HBR",
    type: "PRECISION_RIFLE" as const,
    slot: "PRIMARY" as const,
    ammoType: "HEAVY_ROUNDS" as const,
    rarity: "Standard",
    description:
      "Burst-fire heavy ballistic precision rifle with dual-round delivery system.",
    firepower: 25,
    damage: 13,
    precisionMultiplier: 1.6,
    rateOfFire: 420,
    range: 48,
    accuracy: 59.8,
    hipfireSpread: 2.24,
    adsSpread: 1.29,
    crouchSpreadBonus: 0,
    movingInaccuracy: 81.8,
    handling: 51,
    equipSpeed: 0.94,
    adsSpeed: 0.35,
    reloadSpeed: 2.37,
    weight: 37.5,
    recoil: 44.9,
    aimAssist: 1.1,
    magazineSize: 20,
    zoom: 1.4,
  },
  {
    name: "Stryder M1T",
    type: "PRECISION_RIFLE" as const,
    slot: "PRIMARY" as const,
    ammoType: "LIGHT_ROUNDS" as const,
    rarity: "Standard",
    description: "Fine-tuned semiautomatic precision rifle.",
    firepower: 46.5,
    accuracy: 59.4,
    handling: 39,
    range: 84,
    magazineSize: 12,
    zoom: 1.4,
  },
  {
    name: "V66 Lookout",
    type: "PRECISION_RIFLE" as const,
    slot: "PRIMARY" as const,
    ammoType: "VOLT_BATTERY" as const,
    rarity: "Standard",
    description:
      "Volt-actuated precision rifle with tracking projectiles. Sustained fire overheats the weapon, lowering its rate of fire.",
    firepower: 46.8,
    range: 88,
    accuracy: 66,
    handling: 46,
    zoom: 1.4,
    voltDrain: 3.4,
  },
  {
    name: "B33 Volley Rifle",
    type: "PRECISION_RIFLE" as const,
    slot: "PRIMARY" as const,
    ammoType: "LIGHT_ROUNDS" as const,
    rarity: "Standard",
    description:
      "Semiautomatic precision rifle with three-round burst fire.",
    firepower: 20.7,
    range: 48,
    accuracy: 61.2,
    handling: 45,
    magazineSize: 27,
    zoom: 1.4,
  },

  // === RAILGUNS ===
  {
    name: "V00 Zeus RG",
    type: "RAILGUN" as const,
    slot: "HEAVY" as const,
    ammoType: "VOLT_CELL" as const,
    rarity: "Standard",
    description:
      "Anti-materiel railgun. Fires automatically once fully charged.",
    firepower: 196.5,
    damage: 120,
    precisionMultiplier: 1.5,
    rateOfFire: 90,
    range: 155,
    accuracy: 74.8,
    hipfireSpread: 4.1,
    adsSpread: 0,
    crouchSpreadBonus: 60,
    movingInaccuracy: 90.9,
    handling: 49,
    equipSpeed: 0.9,
    adsSpeed: 0.55,
    reloadSpeed: 3.5,
    weight: 20,
    recoil: 100,
    aimAssist: 1.65,
    zoom: 2.5,
    voltDrain: 50,
    chargeTime: 0.75,
  },
  {
    name: "Ares RG",
    type: "RAILGUN" as const,
    slot: "HEAVY" as const,
    ammoType: "MIPS_ROUNDS" as const,
    rarity: "Standard",
    description:
      "Heavy ballistic railgun. Charges up to fire massive projectile at extreme velocity.",
    firepower: 159.9,
    accuracy: 100.0,
    handling: 47,
    range: 55,
    magazineSize: 4,
    zoom: 2.5,
  },
];

async function main() {
  console.log(`Seeding ${weapons.length} weapons...`);

  for (const weapon of weapons) {
    const slug = slugify(weapon.name);
    const imageUrl = `/weapons/${slug}.png`;
    await db.weapon.upsert({
      where: { name: weapon.name },
      update: { ...weapon, slug, imageUrl },
      create: { ...weapon, slug, imageUrl },
    });
    console.log(`  ✓ ${weapon.name}`);
  }

  console.log(`\nSeeded ${weapons.length} weapons.`);

  // === MODS ===
  const mods: {
    name: string;
    type: "BARREL" | "GRIP" | "MAGAZINE" | "OPTIC" | "SHIELD" | "GENERATOR" | "CHIP";
    rarity: "PRESTIGE" | "SUPERIOR" | "DELUXE" | "ENHANCED" | "STANDARD";
    description?: string;
    price?: number;
    imageUrl?: string;
    isUniversal?: boolean;
    compatibleWeapons: string[];
  }[] = [
    // --- BARREL (14) ---
    { name: "Flechette Split Action", type: "BARREL", rarity: "PRESTIGE", price: 1620, description: "A custom-made mod for the BRRT SMG. Increases stability, handling, and accuracy when firing from the hip", imageUrl: "https://static.wikia.nocookie.net/marathonthegame/images/f/f3/Flechette_Split_Action.png", compatibleWeapons: ["BRRT SMG"] },
    { name: "Lockout Muzzle Brake", type: "BARREL", rarity: "PRESTIGE", price: 1620, description: "A custom-made mod for the BR33 Volley Rifle. Increases movement speed with this weapon. While firing from the hip, this weapon has greatly increased accuracy, stability, and range.", imageUrl: "https://static.wikia.nocookie.net/marathonthegame/images/4/47/Lockout_Muzzle_Brake.png", compatibleWeapons: ["B33 Volley Rifle"] },
    { name: "MIPS Slug Converter", type: "BARREL", rarity: "PRESTIGE", price: 1620, description: "A custom-made mod for the WSTR Combat Shotgun. Increases rate of fire, stability, aim assist, range, and reduces pellet spread. Press to convert shells to a high-powered slug projectile.", imageUrl: "https://static.wikia.nocookie.net/marathonthegame/images/1/14/MIPS_Slug_Converter.png", compatibleWeapons: ["WSTR Combat Shotgun"] },
    { name: "Pinpoint Barrel", type: "BARREL", rarity: "SUPERIOR", price: 540, description: "Greatly increases stability and range.", compatibleWeapons: ["WSTR Combat Shotgun", "Misriah 2442"] },
    { name: "Steady Barrel", type: "BARREL", rarity: "SUPERIOR", price: 540, description: "Greatly increases stability, ready speed, and accuracy while moving.", compatibleWeapons: ["Stryder M1T", "Hardline PR", "Repeater HPR", "Twin Tap HBR", "Longshot", "Outland"] },
    { name: "Suppression Dampener", type: "BARREL", rarity: "DELUXE", price: 207, imageUrl: "https://static.wikia.nocookie.net/marathonthegame/images/4/4b/Suppression_Dampener.png", compatibleWeapons: [] },
    { name: "Precision Barrel", type: "BARREL", rarity: "DELUXE", price: 180, description: "Increased ADS accuracy and range.", imageUrl: "https://static.wikia.nocookie.net/marathonthegame/images/9/94/Precision_Barrel.png", compatibleWeapons: ["BRRT SMG", "Copperhead RF", "Bully SMG", "CE Tactical Sidearm", "Magnum MC"] },
    { name: "Precision Choke", type: "BARREL", rarity: "DELUXE", price: 180, description: "Increases range and aim assist.", imageUrl: "https://static.wikia.nocookie.net/marathonthegame/images/d/da/Precision_Choke.png", compatibleWeapons: ["WSTR Combat Shotgun", "Misriah 2442"] },
    { name: "Farshot Barrel", type: "BARREL", rarity: "ENHANCED", imageUrl: "https://static.wikia.nocookie.net/marathonthegame/images/0/04/Farshot_Barrel.png", compatibleWeapons: [] },
    { name: "Impulse Brake", type: "BARREL", rarity: "ENHANCED", imageUrl: "https://static.wikia.nocookie.net/marathonthegame/images/b/bd/Impluse_Brake.png", compatibleWeapons: [] },
    { name: "Ironhold Barrel", type: "BARREL", rarity: "ENHANCED", price: 60, compatibleWeapons: ["BRRT SMG", "Copperhead RF", "Bully SMG", "CE Tactical Sidearm", "Magnum MC"] },
    { name: "Stabilizing Barrel", type: "BARREL", rarity: "ENHANCED", price: 60, description: "Slightly increases stability.", imageUrl: "https://static.wikia.nocookie.net/marathonthegame/images/7/7b/Stabilizing_Barrel.png", compatibleWeapons: ["V66 Lookout", "V99 Channel Rifle"] },
    { name: "Weighted Barrel", type: "BARREL", rarity: "ENHANCED", price: 540, description: "Slightly increases aim assist.", compatibleWeapons: ["BRRT SMG", "Copperhead RF", "Bully SMG", "CE Tactical Sidearm", "Magnum MC"] },
    { name: "Nano-Suppressor", type: "BARREL", rarity: "ENHANCED", description: "Shots fired from this weapon are silenced.", imageUrl: "https://static.wikia.nocookie.net/marathonthegame/images/0/0a/Marathon_nano-suppressor_enhanced.jpg", compatibleWeapons: ["BRRT SMG", "Copperhead RF", "Bully SMG", "CE Tactical Sidearm", "Magnum MC"] },

    // --- GRIP (2) ---
    { name: "Combat Grip", type: "GRIP", rarity: "DELUXE", price: 180, description: "Increases ADS speed and ready speed.", imageUrl: "https://static.wikia.nocookie.net/marathonthegame/images/e/e2/Combat_Grip.png", compatibleWeapons: ["M77 Assault Rifle", "Overrun AR", "Impact HAR", "V75 Scar"] },
    { name: "Snapshot Grip", type: "GRIP", rarity: "DELUXE", price: 180, description: "Increases accuracy while moving and ADS speed.", imageUrl: "https://static.wikia.nocookie.net/marathonthegame/images/9/93/Snapshot_Grip.png", compatibleWeapons: ["WSTR Combat Shotgun", "Misriah 2442", "V85 Circuit Breaker"] },

    // --- MAGAZINE (10) ---
    { name: "Kingmaker Mag", type: "MAGAZINE", rarity: "PRESTIGE", price: 1620, description: "A unique mod for the Longshot. Increases reload speed and magazine size. Headshots increase rate of fire. Stacks up to three times.", imageUrl: "https://static.wikia.nocookie.net/marathonthegame/images/8/81/Kingmaker_Mag.png", compatibleWeapons: ["Longshot"] },
    { name: "Overclocked Delimiter", type: "MAGAZINE", rarity: "PRESTIGE", price: 1620, description: "A custom-made mod for the V85 Circuit Breaker. Increases magazine size and reload speed. Adds a third level of charge. When fully charged, this weapon has greatly reduced spread, increased damage, and its projectiles ricochet and pierce hostiles.", imageUrl: "https://static.wikia.nocookie.net/marathonthegame/images/5/53/Overclocked_Delimiter.png", compatibleWeapons: ["V85 Circuit Breaker"] },
    { name: "Ram-Page Mag", type: "MAGAZINE", rarity: "PRESTIGE", price: 1620, description: "A custom-made mod for the V75 SCAR. Increases rate of fire, magazine size, and reload speed. Rate of fire no longer decreases as heat builds and projectiles ricochet off surfaces, tracking nearby targets.", imageUrl: "https://static.wikia.nocookie.net/marathonthegame/images/b/ba/Ram-Page_Mag.png", compatibleWeapons: ["V75 Scar"] },
    { name: "Adrenal Feedback Rounds", type: "MAGAZINE", rarity: "PRESTIGE", price: 1620, description: "A custom-made mod for the Hardline PR. Increases Magazine Size. Precision hits reduce your shell's heat and grant a stack of Micro-Adrenaline, increasing Heat Capacity and Agility for a short duration.", imageUrl: "https://static.wikia.nocookie.net/marathonthegame/images/4/4a/Adrenal_Feedback_Rounds.png", compatibleWeapons: ["Hardline PR"] },
    { name: "Rodeo Mag", type: "MAGAZINE", rarity: "PRESTIGE", price: 1620, description: "A custom-made mod for the Bully SMG. Increases rate of fire, stability, and magazine size. This weapon's fire rate greatly increases over time.", imageUrl: "https://static.wikia.nocookie.net/marathonthegame/images/3/37/Rodeo_Mag.png", compatibleWeapons: ["Bully SMG"] },
    { name: "Air-Cooled Chamber", type: "MAGAZINE", rarity: "SUPERIOR", price: 60, description: "Greatly increases reload speed and magazine size.", imageUrl: "https://static.wikia.nocookie.net/marathonthegame/images/3/3b/Air-Cooled_Chamber.png", compatibleWeapons: ["V99 Channel Rifle", "V00 Zeus RG", "V85 Circuit Breaker"] },
    { name: "Hi-Cap Mag", type: "MAGAZINE", rarity: "DELUXE", price: 234, description: "Increases magazine size.", compatibleWeapons: ["Stryder M1T", "Hardline PR", "B33 Volley Rifle", "Twin Tap HBR", "Longshot"] },
    { name: "Steady Mag", type: "MAGAZINE", rarity: "ENHANCED", price: 42, description: "Slightly increases magazine size and stability.", imageUrl: "https://static.wikia.nocookie.net/marathonthegame/images/8/81/Steady_Mag.png", compatibleWeapons: ["CE Tactical Sidearm"] },
    { name: "Turbo Chamber", type: "MAGAZINE", rarity: "ENHANCED", price: 60, compatibleWeapons: ["V22 Volt Thrower", "V11 Punch", "V66 Lookout"] },
    { name: "Slick Mag I", type: "MAGAZINE", rarity: "ENHANCED", price: 60, description: "Slightly increases rate of fire and magazine size.", compatibleWeapons: ["Misriah 2442"] },

    // --- OPTIC (5) ---
    { name: "Lever Overhaul Interface", type: "OPTIC", rarity: "PRESTIGE", price: 1620, description: "A custom-made mod for the Repeater HPR. Increases reload speed and rounds reloaded at a time. Shots on target increase fire rate. This degrades when a shot misses.", imageUrl: "https://static.wikia.nocookie.net/marathonthegame/images/5/56/Lever_Overhaul_Interface.png", compatibleWeapons: ["Repeater HPR"] },
    { name: "Pistol Scope", type: "OPTIC", rarity: "PRESTIGE", price: 1620, description: "A custom-made mod for Magnum MC. Greatly increases ADS speed. Activates a specialized high zoom optic. Precision hits restore a small amount of shields.", imageUrl: "https://static.wikia.nocookie.net/marathonthegame/images/9/96/Pistol_Scope.png", compatibleWeapons: ["Magnum MC"] },
    { name: "Vital Intel", type: "OPTIC", rarity: "PRESTIGE", price: 1620, description: "A custom-made mod for the Stryder M1T. Greatly increases handling and ADS speed. Enables Proximity Sensor on radar. When hostiles are nearby, this weapon has increased handling and accuracy.", imageUrl: "https://static.wikia.nocookie.net/marathonthegame/images/a/a4/Vital_Intel.png", compatibleWeapons: ["Stryder M1T"] },
    { name: "Far Reach Optic", type: "OPTIC", rarity: "DELUXE", price: 207, description: "Increase zoom and ADS accuracy. Rangefinder uses laser pulses to measure distance to the target.", imageUrl: "https://static.wikia.nocookie.net/marathonthegame/images/7/75/Far_Reach_Optic.png", compatibleWeapons: ["Overrun AR", "Impact HAR", "V75 Scar", "BRRT SMG", "Copperhead RF", "Bully SMG"] },
    { name: "Termal Optic", type: "OPTIC", rarity: "DELUXE", price: 207, description: "Increase zoom and ADS accuracy. This sight highlights hostile heat signatures.", compatibleWeapons: ["Stryder M1T", "Hardline PR", "Repeater HPR", "V66 Lookout", "B33 Volley Rifle", "Twin Tap HBR"] },

    // --- SHIELD (4) ---
    { name: "Circuit Shield", type: "SHIELD", rarity: "PRESTIGE", price: 1620, description: "Decreases Recoil by 10%. Damage absorbed by this shield refunds ammo back to the magazine.", imageUrl: "https://static.wikia.nocookie.net/marathonthegame/images/4/49/Circuit_Shield.png", compatibleWeapons: ["Retaliator LMG"] },
    { name: "Control Shield", type: "SHIELD", rarity: "SUPERIOR", price: 621, description: "Greatly increases stability.", imageUrl: "https://static.wikia.nocookie.net/marathonthegame/images/1/14/Control_Shield.png", compatibleWeapons: ["Conquest LMG", "Retaliator LMG", "Demolition HMG"] },
    { name: "Balanced Shield", type: "SHIELD", rarity: "DELUXE", price: 207, description: "Increases ready speed and movement speed with this weapon.", imageUrl: "https://static.wikia.nocookie.net/marathonthegame/images/e/ec/Balanced_Shield.png", compatibleWeapons: ["Conquest LMG", "Retaliator LMG", "Demolition HMG"] },
    { name: "Duelist Shield", type: "SHIELD", rarity: "ENHANCED", price: 69, description: "Slightly increases accuracy while moving and ADS speed.", imageUrl: "https://static.wikia.nocookie.net/marathonthegame/images/7/71/Duelist_Shield.png", compatibleWeapons: ["Conquest LMG", "Retaliator LMG", "Demolition HMG"] },

    // --- GENERATOR (2) ---
    { name: "Overclocked Generator", type: "GENERATOR", rarity: "PRESTIGE", compatibleWeapons: ["V00 Zeus RG"] },
    { name: "Stabilizing Generator", type: "GENERATOR", rarity: "SUPERIOR", compatibleWeapons: ["Ares RG", "V00 Zeus RG"] },

    // --- CHIP (9: 8 universal + 1 non-universal) ---
    { name: "See ya", type: "CHIP", rarity: "SUPERIOR", price: 621, description: "Reloading this weapon when the magazine is empty causes you to become briefly invisible.", isUniversal: true, compatibleWeapons: [] },
    { name: "Bounty", type: "CHIP", rarity: "DELUXE", price: 207, description: "Eliminating UESC pays you a considerable amount of credits.", isUniversal: true, compatibleWeapons: [] },
    { name: "Torch Bug", type: "CHIP", rarity: "DELUXE", price: 207, description: "Eliminating a hostile causes them to explode.", imageUrl: "https://static.wikia.nocookie.net/marathonthegame/images/f/ff/Torch_Bug.png", isUniversal: true, compatibleWeapons: [] },
    { name: "Bounty Hunter", type: "CHIP", rarity: "ENHANCED", price: 69, description: "Eliminating UESC pays you a small amount of credits.", isUniversal: true, compatibleWeapons: [] },
    { name: "Swarm Directive", type: "CHIP", rarity: "ENHANCED", price: 69, description: "Precision eliminations with this weapon spawn a few flechette seekers that heal you when damaging hostiles.", isUniversal: true, compatibleWeapons: [] },
    { name: "Last Resort", type: "CHIP", rarity: "ENHANCED", price: 69, description: "While you are Overheated, non-precision damage is increased by a moderate amount.", imageUrl: "https://static.wikia.nocookie.net/marathonthegame/images/8/88/Last_Resort.png", isUniversal: true, compatibleWeapons: [] },
    { name: "Eyes On Fire", type: "CHIP", rarity: "STANDARD", price: 60, imageUrl: "https://static.wikia.nocookie.net/marathonthegame/images/9/94/Eyes_On_Fire.png", isUniversal: true, compatibleWeapons: [] },
    { name: "Endless Runner", type: "CHIP", rarity: "STANDARD", price: 23, imageUrl: "https://static.wikia.nocookie.net/marathonthegame/images/d/df/Endless_Runner.png", isUniversal: true, compatibleWeapons: [] },
    { name: "Veilshot Chip", type: "CHIP", rarity: "ENHANCED", price: 60, compatibleWeapons: ["Conquest LMG"] },
  ];

  console.log(`\nSeeding ${mods.length} mods...`);

  // Build weapon name → id lookup
  const allWeapons = await db.weapon.findMany({ select: { id: true, name: true } });
  const weaponMap = new Map(allWeapons.map((w) => [w.name, w.id]));

  for (const mod of mods) {
    const slug = slugify(mod.name);
    const data = {
      slug,
      type: mod.type,
      rarity: mod.rarity,
      description: mod.description ?? null,
      price: mod.price ?? null,
      imageUrl: mod.imageUrl ?? null,
      isUniversal: mod.isUniversal ?? false,
    };
    const upserted = await db.mod.upsert({
      where: { name: mod.name },
      update: data,
      create: { name: mod.name, ...data },
    });

    // Create junction rows for non-universal mods
    for (const weaponName of mod.compatibleWeapons) {
      const weaponId = weaponMap.get(weaponName);
      if (!weaponId) {
        console.warn(`  ⚠ Weapon not found: "${weaponName}" (mod: ${mod.name})`);
        continue;
      }
      await db.weaponMod.upsert({
        where: { weaponId_modId: { weaponId, modId: upserted.id } },
        update: {},
        create: { weaponId, modId: upserted.id },
      });
    }

    console.log(`  ✓ ${mod.name} (${mod.compatibleWeapons.length} weapons)`);
  }

  console.log(`\nSeeded ${mods.length} mods.`);
}

main()
  .then(() => db.$disconnect())
  .catch(async (e) => {
    console.error(e);
    await db.$disconnect();
    process.exit(1);
  });
